# Generated by Django 3.2.5 on 2022-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicen_app', '0005_contact_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
