# Generated by Django 3.2.5 on 2022-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicen_app', '0006_prescription_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='longterm',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='shortterm',
            field=models.BooleanField(null=True),
        ),
    ]
