# Generated by Django 3.2.5 on 2022-04-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicen_app', '0007_auto_20220410_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='longterm',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='shortterm',
        ),
        migrations.AddField(
            model_name='prescription',
            name='term',
            field=models.CharField(choices=[('longterm', 'longterm'), ('shortterm', 'shortterm')], default='shortterm', max_length=200),
        ),
    ]
