# Generated by Django 3.2.5 on 2022-04-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicen_app', '0008_auto_20220411_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctorid',
            field=models.IntegerField(null=True),
        ),
    ]
