# Generated by Django 3.2.5 on 2022-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicen_app', '0009_doctor_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
