# Generated by Django 3.2.5 on 2022-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicen_app', '0010_alter_doctor_doctorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='desc',
            field=models.CharField(default='Department', max_length=100, null=None),
        ),
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.CharField(default='Department', max_length=500, null=None),
        ),
    ]
