# Generated by Django 3.2.5 on 2022-04-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicen_app', '0011_auto_20220411_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='img',
            field=models.CharField(default='Department', max_length=500, null=None),
        ),
    ]
